# Ethereum Mainnet Configuration

# Disable InfluxDB since it's not available in the container
# # InfluxDB is completely disabled by not including the section
# If you want to enable it later, uncomment and configure:
# [influxdb]
# # url = "http://localhost:8086"
# # database = "loom_metrics"
# # tags = { environment = "production", network = "ethereum" }

[clients.local]
# Use a more reliable RPC provider with higher rate limits
url = "https://eth-mainnet.g.alchemy.com/v2/E08VrhfX0pO4GT_tJsUQpjKIXu_D1S05"
transport = "http"
node = "geth"
# Add backup RPC URLs
backup_urls = [
  "https://eth-mainnet.g.alchemy.com/v2/E08VrhfX0pO4GT_tJsUQpjKIXu_D1S05"
]

[blockchains.ethereum]
chain_id = 1

[signers.env_signer]
type = "env"
blockchain = "ethereum"

[encoders.multicaller]
type = "swapstep"
address = "0x3dd35b4da6534230ff53048f7477f17f7f4e7a70"  # Use existing multicaller address or deploy a new one

[actors.node]
# Disable real-time pool monitoring (new) as it requires subscriptions
ethereum = { bc = "ethereum", client = "local" }

# Disable mempool actor as it requires subscriptions
# [actors.mempool]
# ethereum = { bc = "ethereum", client = "local" }

[actors.price]
ethereum = { bc = "ethereum", client = "local" }

[actors.pools]
# Disable real-time pool monitoring (new) as it requires subscriptions
ethereum = { bc = "ethereum", client = "local", history = true, new = false, protocol = true }

[actors.noncebalance]
ethereum = { bc = "ethereum", client = "local" }

[actors.estimator]
# Use regular broadcaster instead of flashbots to avoid subscription issues
ethereum = { type = "evm", bc = "ethereum", client = "local", encoder = "multicaller" }

[actors.broadcaster]
# Use flashbots broadcaster with subscription disabled
ethereum = { type = "flashbots", bc = "ethereum", client = "local", smart = true }

[backrun_strategy]
eoa = "0xb1c0aa420da988ef0635064782dec493686c1a5e"  # Derived from the private key provided
smart = true
chain_id = 1

[backrun_strategy.ethereum_config]
min_profit_wei = "1000000000000000"
priority_fee = "100000000"
max_gas_price = "30000000000"
max_capital_usd = 100000
max_capital_wei = "41000000000000000000"  # ~$100,000 worth of ETH at $2,440/ETH
tips_percentage = 10  # 10% of profits as tips

# Ethereum Mainnet Tokens
[tokens.ethereum]
# Native ETH token (required for proper operation)
eth = { address = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE", symbol = "ETH", decimals = 18, basic = true, middle = true }
# Correct token addresses for Ethereum mainnet
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", symbol = "WETH", decimals = 18, basic = true, middle = true }
usdt = { address = "0xdAC17F958D2ee523a2206206994597C13D831ec7", symbol = "USDT", decimals = 6, basic = true, middle = true }
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", symbol = "USDC", decimals = 6, basic = true, middle = true }
dai = { address = "0x6B175474E89094C44Da98b954EedeAC495271d0F", symbol = "DAI", decimals = 18, basic = true, middle = true }
wbtc = { address = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599", symbol = "WBTC", decimals = 8, basic = true, middle = false }
reth = { address = "0xae78736Cd615f374D3085123A210448E74Fc6393", symbol = "rETH", decimals = 18, basic = true, middle = false }
steth = { address = "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84", symbol = "stETH", decimals = 18, basic = true, middle = false }
wsteth = { address = "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0", symbol = "wstETH", decimals = 18, basic = true, middle = false }
cbeth = { address = "0xBe9895146f7AF43049ca1c1AE358B0541Ea49704", symbol = "cbETH", decimals = 18, basic = false, middle = false }
# Additional tokens
link = { address = "0x514910771AF9Ca656af840dff83E8264EcF986CA", symbol = "LINK", decimals = 18, basic = true, middle = false }
uni = { address = "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984", symbol = "UNI", decimals = 18, basic = true, middle = false }
aave = { address = "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9", symbol = "AAVE", decimals = 18, basic = true, middle = false }
matic = { address = "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0", symbol = "MATIC", decimals = 18, basic = true, middle = false }
crv = { address = "0xD533a949740bb3306d119CC777fa900bA034cd52", symbol = "CRV", decimals = 18, basic = true, middle = false }