[package]
name = "loom-core-topology-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-transport-ws.workspace = true
alloy-provider.workspace = true
tokio.workspace = true
tracing.workspace = true
