[package]
name = "loom_base"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
alloy-primitives = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
influxdb = { workspace = true }
num_cpus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

loom = { path = "../../" }
loom-core-actors = { path = "../../crates/core/actors" }
loom-core-router = { path = "../../crates/core/router" }
loom-core-topology = { path = "../../crates/core/topology" }
loom-defi-health-monitor = { path = "../../crates/defi/health-monitor" }
loom-evm-db = { path = "../../crates/evm/db" }
loom-execution-multicaller = { path = "../../crates/execution/multicaller" }
loom-metrics = { path = "../../crates/metrics" }
loom-strategy-backrun = { path = "../../crates/strategy/backrun" }
loom-strategy-merger = { path = "../../crates/strategy/merger" }
loom-strategy-simple-arb = { path = "../../crates/strategy/simple_arb" }
loom-types-entities = { path = "../../crates/types/entities" }
loom-types-events = { path = "../../crates/types/events" }