[package]
name = "loom_base"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
alloy-primitives = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
influxdb = { workspace = true }
num_cpus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

loom = { workspace = true, features = ["full", "strategy-full"] }
loom-core-actors = { workspace = true }
loom-core-router = { workspace = true }
loom-core-topology = { workspace = true }
loom-defi-health-monitor = { workspace = true }
loom-evm-db = { workspace = true }
loom-execution-multicaller = { workspace = true }
loom-metrics = { workspace = true }
loom-strategy-backrun = { workspace = true }
loom-strategy-merger = { workspace = true }
loom-strategy-simple-arb = { workspace = true }
loom-types-entities = { workspace = true }
loom-types-events = { workspace = true }